export const LIMPEZA_TABLES = [
  { key: 'inscricoes', label: 'Inscrições', model: 'inscricao', icon: '📝', safe: true },
  { key: 'posts', label: 'Posts', model: 'post', icon: '📰', safe: true },
  { key: 'eventos', label: 'Eventos', model: 'evento', icon: '📅', safe: true },
  { key: 'chatSessoes', label: 'Sessões de Chat', model: 'chatSessao', icon: '💬', safe: true },
  { key: 'chatMensagens', label: 'Mensagens de Chat', model: 'chatMensagem', icon: '💬', safe: true },
  { key: 'alertasInteresse', label: 'Alertas de Interesse', model: 'alertaInteresse', icon: '🔔', safe: true },
  { key: 'favoritos', label: 'Favoritos', model: 'favorito', icon: '⭐', safe: true },
  { key: 'notificacoes', label: 'Notificações', model: 'notificacao', icon: '🔔', safe: true },
  { key: 'auditLogs', label: 'Logs de Auditoria', model: 'auditLog', icon: '📋', safe: true },
  { key: 'syncLogs', label: 'Logs de Sync', model: 'syncLog', icon: '🔄', safe: true },
  { key: 'jobs', label: 'Jobs', model: 'job', icon: '⚙️', safe: true },
  { key: 'ragChunks', label: 'Chunks RAG', model: 'ragChunk', icon: '📄', safe: true },
  { key: 'ragDocumentos', label: 'Documentos RAG', model: 'ragDocumento', icon: '📄', safe: true },
  { key: 'iaRevisoes', label: 'Revisões IA', model: 'iaRevisao', icon: '🤖', safe: true },
  { key: 'editalExplicacoes', label: 'Explicações Edital', model: 'editalExplicacao', icon: '📖', safe: true },
  { key: 'editalResumoVersoes', label: 'Versões Resumo Edital', model: 'editalResumoVersao', icon: '📝', safe: true },
  { key: 'projetoFaqs', label: 'FAQs de Projetos', model: 'projetoFaq', icon: '❓', safe: true },
  { key: 'projetoCursos', label: 'Cursos de Projetos', model: 'projetoCurso', icon: '🎓', safe: true },
  { key: 'projetoTags', label: 'Tags de Projetos', model: 'projetoTag', icon: '🏷️', safe: true },
  { key: 'editalTags', label: 'Tags de Editais', model: 'editalTag', icon: '🏷️', safe: true },
  { key: 'projectCoordinators', label: 'Coordenadores Projeto', model: 'projectCoordinator', icon: '👥', safe: true },
  { key: 'userPermissions', label: 'Permissões Usuário', model: 'userPermission', icon: '🔐', safe: true },
  { key: 'siteConfigs', label: 'Configurações Site', model: 'siteConfig', icon: '⚙️', safe: false },
  { key: 'editais', label: 'Editais', model: 'edital', icon: '📋', safe: false },
  { key: 'projetos', label: 'Projetos', model: 'projeto', icon: '📁', safe: false },
  { key: 'usuarios', label: 'Usuários', model: 'user', icon: '👤', safe: false },
];
